

version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: sylvain
      POSTGRES_PASSWORD:
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"

volumes:
  postgres-data:
